#come from https://github.com/1810-java-blake/demos/tree/master/week4/LeagueOfLegendsApi
# this likely will not work anymore because the buildspec needs to specify the runtime in the current version of codebuild
version: 0.2

phases:
  post_build:
    commands:
      - cd week4/LeagueOfLegendsApi && mvn clean package
artifacts:
  files:
    - '**/*'
  base-directory: 'week4/LeagueOfLegendsApi/target/LeagueOfLegendsApi'
