#pulled from: https://github.com/btkruppa/angular-redux-demo
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/angular-redux-demo'
